### index
GET {{app}}

### success
POST {{app}}/success
Content-Type: application/json

{
  "key": "1"
}

### fail
POST {{app}}/fail
Content-Type: application/json

{
  "key": "1"
}

### sleep
GET {{app}}/sleep/1
Content-Type: application/json

###
### deposit
POST {{app}}/signature
Content-Type: application/json

{
  "key": "13653cb1-1cf5-4c43-b123-611dd8f720d7",
  "contentType": "application/json; charset=utf-8",
  "keyId": "bc4d3b07-e8b4-4ed0-97f8-7fc188b7b12e",
  "body": "{\"deviceType\":\"WEB\",\"identity\": \"depositTommyTest0000000001\"}"
}

###
### withdraw
POST {{app}}/signature
Content-Type: application/json

{
  "key": "13653cb1-1cf5-4c43-b123-611dd8f720d7",
  "contentType": "application/json; charset=utf-8",
  "keyId": "bc4d3b07-e8b4-4ed0-97f8-7fc188b7b12e",
  "body": "{\"referenceId\":\"tommyWithdrawal27894995179400\",\"deviceType\":\"WEB\",\"bankCode\":\"ICBC\",\"bankBranch\":\"北京北京\",\"cardHolderName\":\"湯米\",\"cardNumber\":\"012345678901234567\",\"amount\":100.00}"
}

###
###
###
###
###
###
###





