# This workflow will build a Java project with Maven

# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# https://www.schakko.de/2020/12/19/using-github-workflow-with-maven-dependencies-from-a-private-github-package-registry/
name: Java CI with Maven
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    Publish:
    needs: Build
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: '11'

        - name: Create GitHub Release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          with:
            tag_name: v${{github.run_number}}
            release_name: Release V${{github.run_number}}

        - name: Update version
          run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false

        - name: Publish to GitHub Packages Apache Maven
          run: mvn -B deploy -DskipTests --file pom.xml
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}






#name: Publish to Github Packages
#on:
#  workflow_dispatch:
#
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Publish to Github Packages
#        run: ./gradlew publish --stacktrace
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GH_USER_NAME: ${{ secrets.GH_USER_NAME }}
#          GH_PACKAGES_UPLOAD_TOKEN: ${{ secrets.GH_PACKAGES_UPLOAD_TOKEN }}
### https://blog.dipien.com/how-to-publish-your-internal-artifacts-to-github-packages-5447e7e82e80